### ISSUE TITLE
 Connection error

### ISSUE THREAD

**Issue by wuke37** [kaistsystemsbiology/DeepProZyme#2]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-b260df03e064> in <module>
----> 1 proteinDataset = DeepECDataset(data_X=input_seqs, data_Y=pseudo_labels, explainECs=explainECs, pred=True)
      2 proteinDataloader = DataLoader(proteinDataset, batch_size=batch_size, shuffle=False)
      3 
      4 y_pred, y_score = run_neural_net(model, proteinDataloader, pred_thrd, device=device)
      5 failed_cases = save_dl_result(y_pred, y_score, input_ids, explainECs, output_dir+'/tmp')

[~/project/DeepProZyme/deepec/data_loader.py](https://vscode-remote+ssh-002dremote-002b219-002e223-002e172-002e133.vscode-resource.vscode-cdn.net/home/wuke/project/DeepProZyme/~/project/DeepProZyme/deepec/data_loader.py) in __init__(self, data_X, data_Y, explainECs, tokenizer_name, max_length, pred)
      8 class DeepECDataset(Dataset):
      9     def __init__(self, data_X, data_Y, explainECs, tokenizer_name='Rostlab/prot_bert_bfd', max_length=1000, pred=False):
---> 10         self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name, do_lower_case=False)
     11         self.max_length = max_length
     12         self.data_X = data_X

[~/anaconda3/envs/kcat_pre/lib/python3.7/site-packages/transformers/tokenization_auto.py](https://vscode-remote+ssh-002dremote-002b219-002e223-002e172-002e133.vscode-resource.vscode-cdn.net/home/wuke/project/DeepProZyme/~/anaconda3/envs/kcat_pre/lib/python3.7/site-packages/transformers/tokenization_auto.py) in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    304         config = kwargs.pop("config", None)
    305         if not isinstance(config, PretrainedConfig):
--> 306             config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
    307 
    308         if "bert-base-japanese" in str(pretrained_model_name_or_path):

[~/anaconda3/envs/kcat_pre/lib/python3.7/site-packages/transformers/configuration_auto.py](https://vscode-remote+ssh-002dremote-002b219-002e223-002e172-002e133.vscode-resource.vscode-cdn.net/home/wuke/project/DeepProZyme/~/anaconda3/envs/kcat_pre/lib/python3.7/site-packages/transformers/configuration_auto.py) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    331             {'foo': False}
...
-> 1125                         "Connection error, and we cannot find the requested files in the cached path."
   1126                         " Please try again or make sure your Internet connection is on."
   1127                     )

ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

=.= sorry for this

**Comment by YTYGdemc** [comment]
The same error appears to me, have u solved the error ?
